create table if not exists public.shifts (
 id bigint generated by default as identity primary key,
 shift_date date not null,
 employee text not null,
 team text not null,
 status text not null default 'Schicht',
 shift_text text not null default '',
 updated_at timestamptz not null default now(),
 unique (shift_date, employee)
);
alter table public.shifts enable row level security;
